name: Run checks

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '2.7', '3.5', '3.6', '3.7', '3.8', '3.9' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements.txt
      - name: Run all check in Linux
        if: runner.os == 'Linux'
        run: make check
      - name: Run pytest only in Windows (Makefile doesn't work in mingw32)
        if: runner.os == 'Windows'
        run: py.test --cov-report term-missing --cov=uflash tests/
